CREATE TABLE IF NOT EXISTS `buffs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `source_id` INT NOT NULL,
  `internal_name` VARCHAR(255) NOT NULL,
  `english_name` VARCHAR(255) DEFAULT NULL,
  `name_zh` VARCHAR(255) DEFAULT NULL,
  `tooltip_en` TEXT DEFAULT NULL,
  `tooltip_zh` TEXT DEFAULT NULL,
  `image` VARCHAR(500) DEFAULT NULL,
  `buff_type` VARCHAR(64) DEFAULT NULL,
  `source_item_count` INT NOT NULL DEFAULT 0,
  `immune_npc_count` INT NOT NULL DEFAULT 0,
  `source_items_json` LONGTEXT DEFAULT NULL,
  `immune_npc_sample_json` LONGTEXT DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_buffs_source_id` (`source_id`),
  UNIQUE KEY `uk_buffs_internal_name` (`internal_name`),
  INDEX `idx_buffs_name_zh` (`name_zh`),
  INDEX `idx_buffs_english_name` (`english_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `buff_source_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `buff_id` BIGINT NOT NULL,
  `source_item_id` INT DEFAULT NULL,
  `source_item_internal_name` VARCHAR(255) DEFAULT NULL,
  `source_item_name` VARCHAR(255) DEFAULT NULL,
  `item_id` BIGINT DEFAULT NULL,
  `buff_time` INT DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_buff_source_items` (`buff_id`, `sort_order`),
  INDEX `idx_buff_source_items_item_id` (`item_id`),
  INDEX `idx_buff_source_items_internal_name` (`source_item_internal_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `npcs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `source_id` INT NOT NULL,
  `internal_name` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `net_id` INT DEFAULT NULL,
  `npc_type` INT DEFAULT NULL,
  `ai_style` INT DEFAULT NULL,
  `damage` INT DEFAULT NULL,
  `defense` INT DEFAULT NULL,
  `life_max` INT DEFAULT NULL,
  `knock_back_resist` DECIMAL(10,4) DEFAULT NULL,
  `width` INT DEFAULT NULL,
  `height` INT DEFAULT NULL,
  `scale` DECIMAL(10,4) DEFAULT NULL,
  `value` INT DEFAULT NULL,
  `buff_immune` TEXT DEFAULT NULL,
  `raw_json` LONGTEXT DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_npcs_source_id` (`source_id`),
  UNIQUE KEY `uk_npcs_internal_name` (`internal_name`),
  INDEX `idx_npcs_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `projectiles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `source_id` INT NOT NULL,
  `internal_name` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `ai_style` INT DEFAULT NULL,
  `damage` INT DEFAULT NULL,
  `knock_back` DECIMAL(10,4) DEFAULT NULL,
  `penetrate` INT DEFAULT NULL,
  `time_left` INT DEFAULT NULL,
  `width` INT DEFAULT NULL,
  `height` INT DEFAULT NULL,
  `scale` DECIMAL(10,4) DEFAULT NULL,
  `friendly` TINYINT(1) NOT NULL DEFAULT 0,
  `hostile` TINYINT(1) NOT NULL DEFAULT 0,
  `tile_collide` TINYINT(1) NOT NULL DEFAULT 1,
  `raw_json` LONGTEXT DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_projectiles_source_id` (`source_id`),
  UNIQUE KEY `uk_projectiles_internal_name` (`internal_name`),
  INDEX `idx_projectiles_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `armor_sets` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `source_key` VARCHAR(255) NOT NULL,
  `text_key` VARCHAR(255) DEFAULT NULL,
  `benefit_expression` VARCHAR(500) DEFAULT NULL,
  `primary_part` VARCHAR(255) DEFAULT NULL,
  `set_count` INT NOT NULL DEFAULT 0,
  `unique_item_count` INT NOT NULL DEFAULT 0,
  `sets_json` LONGTEXT DEFAULT NULL,
  `unique_item_ids_json` LONGTEXT DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_armor_sets_source_key` (`source_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `armor_set_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `armor_set_id` BIGINT NOT NULL,
  `set_variant_index` INT NOT NULL DEFAULT 0,
  `part_index` INT NOT NULL DEFAULT 0,
  `source_item_id` INT DEFAULT NULL,
  `item_id` BIGINT DEFAULT NULL,
  `item_internal_name` VARCHAR(255) DEFAULT NULL,
  `item_name` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_armor_set_items` (`armor_set_id`, `set_variant_index`, `part_index`),
  INDEX `idx_armor_set_items_item_id` (`item_id`),
  INDEX `idx_armor_set_items_internal_name` (`item_internal_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
