CREATE TABLE IF NOT EXISTS `category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `top_type` VARCHAR(32) NOT NULL DEFAULT '',
  `sort` INT DEFAULT 0,
  `description` TEXT,
  `icon` VARCHAR(255),
  `status` INT DEFAULT 1,
  `creator_id` BIGINT,
  `deleted` TINYINT DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_category_parent_id` (`parent_id`),
  UNIQUE KEY `uk_category_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `internal_name` VARCHAR(255) DEFAULT NULL,
  `image` VARCHAR(500) DEFAULT NULL,
  `category_id` BIGINT DEFAULT NULL,
  `description` TEXT,
  `damage` INT DEFAULT NULL,
  `defense` INT DEFAULT NULL,
  `knockback` INT DEFAULT NULL,
  `use_time` INT DEFAULT NULL,
  `width` INT DEFAULT NULL,
  `height` INT DEFAULT NULL,
  `buy` INT DEFAULT NULL,
  `sell` INT DEFAULT NULL,
  `tooltip` TEXT,
  `rarity_id` BIGINT DEFAULT NULL,
  `game_period_id` BIGINT DEFAULT NULL,
  `game_model_id` BIGINT DEFAULT NULL,
  `is_stackable` TINYINT(1) DEFAULT 0,
  `stack_size` INT DEFAULT 1,
  `status` INT DEFAULT 1,
  `deleted` TINYINT DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_items_category_id` (`category_id`),
  INDEX `idx_items_name` (`name`),
  INDEX `idx_items_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
