CREATE TABLE IF NOT EXISTS `shimmer_item_transforms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `context_code` VARCHAR(100) NOT NULL,
  `input_kind` VARCHAR(32) NOT NULL,
  `input_name_en` VARCHAR(255) DEFAULT NULL,
  `input_name_zh` VARCHAR(255) DEFAULT NULL,
  `input_internal_name` VARCHAR(255) DEFAULT NULL,
  `output_kind` VARCHAR(32) NOT NULL,
  `output_name_en` VARCHAR(255) DEFAULT NULL,
  `output_name_zh` VARCHAR(255) DEFAULT NULL,
  `output_internal_name` VARCHAR(255) DEFAULT NULL,
  `conditions_json` LONGTEXT DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `source_provider` VARCHAR(64) DEFAULT NULL,
  `source_page` VARCHAR(255) DEFAULT NULL,
  `source_revision_timestamp` DATETIME DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shimmer_item_transforms_source` (`source_provider`, `source_page`),
  INDEX `idx_shimmer_item_transforms_context` (`context_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `shimmer_decraft_rules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `context_code` VARCHAR(100) NOT NULL,
  `rule_type` VARCHAR(64) NOT NULL,
  `group_label` VARCHAR(255) DEFAULT NULL,
  `input_kind` VARCHAR(32) NOT NULL,
  `input_name_en` VARCHAR(255) DEFAULT NULL,
  `input_name_zh` VARCHAR(255) DEFAULT NULL,
  `input_internal_name` VARCHAR(255) DEFAULT NULL,
  `outputs_json` LONGTEXT DEFAULT NULL,
  `conditions_json` LONGTEXT DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `source_provider` VARCHAR(64) DEFAULT NULL,
  `source_page` VARCHAR(255) DEFAULT NULL,
  `source_revision_timestamp` DATETIME DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shimmer_decraft_rules_source` (`source_provider`, `source_page`),
  INDEX `idx_shimmer_decraft_rules_context` (`context_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `shimmer_entity_transforms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `context_code` VARCHAR(100) NOT NULL,
  `transform_group` VARCHAR(64) NOT NULL,
  `input_entity_type` VARCHAR(32) DEFAULT NULL,
  `input_name_en` VARCHAR(255) DEFAULT NULL,
  `input_name_zh` VARCHAR(255) DEFAULT NULL,
  `input_internal_name` VARCHAR(255) DEFAULT NULL,
  `output_entity_type` VARCHAR(32) DEFAULT NULL,
  `output_name_en` VARCHAR(255) DEFAULT NULL,
  `output_name_zh` VARCHAR(255) DEFAULT NULL,
  `output_internal_name` VARCHAR(255) DEFAULT NULL,
  `source_provider` VARCHAR(64) DEFAULT NULL,
  `source_page` VARCHAR(255) DEFAULT NULL,
  `source_revision_timestamp` DATETIME DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shimmer_entity_transforms_source` (`source_provider`, `source_page`),
  INDEX `idx_shimmer_entity_transforms_context` (`context_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `shimmer_npc_transforms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `context_code` VARCHAR(100) NOT NULL,
  `npc_name_en` VARCHAR(255) DEFAULT NULL,
  `npc_name_zh` VARCHAR(255) DEFAULT NULL,
  `npc_internal_name` VARCHAR(255) DEFAULT NULL,
  `appearance_variant` VARCHAR(64) DEFAULT NULL,
  `effect_type` VARCHAR(64) DEFAULT NULL,
  `variant_image_url` VARCHAR(500) DEFAULT NULL,
  `variant_image_alt` VARCHAR(255) DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `source_provider` VARCHAR(64) DEFAULT NULL,
  `source_page` VARCHAR(255) DEFAULT NULL,
  `source_revision_timestamp` DATETIME DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_shimmer_npc_transforms_source` (`source_provider`, `source_page`),
  INDEX `idx_shimmer_npc_transforms_context` (`context_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
