CREATE TABLE IF NOT EXISTS `audio_assets` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `asset_id` VARCHAR(255) NOT NULL,
  `shard` VARCHAR(32) NOT NULL,
  `kind` VARCHAR(64) NOT NULL,
  `source_key` VARCHAR(255) DEFAULT NULL,
  `file_title` VARCHAR(255) DEFAULT NULL,
  `wiki_file_url` VARCHAR(500) DEFAULT NULL,
  `source_url` VARCHAR(500) DEFAULT NULL,
  `local_path` VARCHAR(500) DEFAULT NULL,
  `absolute_local_path` VARCHAR(700) DEFAULT NULL,
  `mime` VARCHAR(128) DEFAULT NULL,
  `size_bytes` BIGINT DEFAULT NULL,
  `sha256` CHAR(64) DEFAULT NULL,
  `provider` VARCHAR(64) NOT NULL DEFAULT 'wiki_gg',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `last_verified_at` DATETIME DEFAULT NULL,
  `crawl_report_path` VARCHAR(500) DEFAULT NULL,
  `raw_json` LONGTEXT DEFAULT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_audio_assets_asset_id` (`asset_id`),
  INDEX `idx_audio_assets_shard` (`shard`),
  INDEX `idx_audio_assets_kind` (`kind`),
  INDEX `idx_audio_assets_sha256` (`sha256`),
  INDEX `idx_audio_assets_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `audio_asset_links` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `audio_asset_id` BIGINT NOT NULL,
  `entity_type` VARCHAR(64) NOT NULL,
  `entity_id` BIGINT DEFAULT NULL,
  `source_key` VARCHAR(255) DEFAULT NULL,
  `relation_type` VARCHAR(64) NOT NULL,
  `match_status` VARCHAR(32) NOT NULL DEFAULT 'unmatched',
  `match_reason` VARCHAR(500) DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_audio_asset_links_identity` (`audio_asset_id`, `entity_type`, `source_key`, `relation_type`),
  INDEX `idx_audio_asset_links_asset` (`audio_asset_id`),
  INDEX `idx_audio_asset_links_entity` (`entity_type`, `entity_id`),
  INDEX `idx_audio_asset_links_match` (`match_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
