import type { CrawlerMonitorOverview, CrawlerMonitorReportDetail, CrawlerMonitorTestState } from '~/types/crawlerMonitor'

const overview: CrawlerMonitorOverview = {
  generatedAt: '2026-04-27T00:00:00Z',
  repoRoot: 'G:/ClaudeCode/TerraPedia-dev',
  daemon: {
    found: true,
    readable: true,
    path: 'reports/backend-refresh/backend-refresh-daemon.heartbeat.json',
    payload: {
      status: 'running',
      activeChildPid: 1300,
    },
  },
  latestRun: {
    found: true,
    readable: true,
    totalActions: 3,
    completedActions: 2,
    failedActions: 1,
    actions: [
      {
        id: 'wiki-core-refresh',
        runner: 'node',
        status: 'running',
        phase: 'apply',
        message: 'running wiki action 2 of 5',
        queue: 'active shard',
        dataStage: 'wiki API -> generated core JSON',
        nextStep: 'Keep backend-refresh heartbeat current',
        current: 2,
        total: 5,
        startedAt: '2026-04-27T00:00:00Z',
        batchOffset: 100,
        batchLimit: 100,
        overallCurrent: 102,
        overallTotal: 6131,
        percent: 40,
        lastHeartbeatAt: '2026-04-27T00:00:30Z',
        childStatusPath: 'reports/backend-refresh/history/backend-data-refresh.runtime/wiki-core-refresh.child-status.json',
        durationMs: 2400,
      },
    ],
  },
  refreshStale: true,
  refreshLastActivityAt: '2026-04-26T00:00:00Z',
  refreshStaleThresholdMs: 86400000,
  refreshStaleReason: 'backend-refresh monitor has no activity for more than 24 hours',
  imageNormalization: {
    latestImageLineageReport: 'reports/audit/image-source-lineage-2026-05-08-minio-post-normalization-v4.json',
    lastCanonicalSyncAt: '2026-05-08T09:11:38.895Z',
    npcWrongPrefixCount: 0,
    projectileWrongPrefixCount: 0,
    npcWikiOnlyCount: 0,
    projectileWikiOnlyCount: 1,
    legacyExemptionCount: 0,
  },
  history: [],
  recentReports: [
    {
      name: 'TEST-com.terraria.skills.CrawlerMonitorServiceImplTest.xml',
      path: 'back/target/surefire-reports/TEST-com.terraria.skills.CrawlerMonitorServiceImplTest.xml',
      category: 'test',
      updatedAt: '2026-04-28T02:00:00Z',
      sizeBytes: 2400,
    },
  ],
  architectureLayers: [
    {
      id: 'sync-report',
      label: 'Sync / Report Evidence',
      status: 'success',
      fileCount: 1,
      readableCount: 1,
      missingCount: 0,
      errorCount: 0,
      updatedAt: '2026-04-29T08:00:00Z',
      summary: '1/1 readable',
      files: [
        {
          label: 'Relation health reports',
          path: 'reports/relation/relation-health*.json',
          latestPath: 'reports/relation/relation-health-2026-04-29.json',
          found: true,
          readable: true,
          count: 4,
          sizeBytes: 1024,
          updatedAt: '2026-04-29T08:00:00Z',
        },
      ],
    },
  ],
  registeredTasks: [
    {
      id: 'item-pages-refresh',
      label: 'Item page crawl shard',
      status: 'running',
      priority: 'p0',
      lane: 'fetch',
      queueState: 'fetched 43/100 item page(s); ok=43; failed=0',
      nextStep: 'Monitor the active shard, then retry failures and run transform-standardize.',
      dataStage: 'wiki item pages -> crawler JSON',
      current: 43,
      total: 100,
      overallCurrent: 1943,
      overallTotal: 6131,
      pending: 4188,
      failed: 0,
      percent: 43,
      inputPath: 'wiki item pages',
      outputPath: 'data/generated/wiki-item-pages*.json',
      progressPath: 'data/generated/wiki-sync-progress.latest.json',
      progressSource: 'data/generated/wiki-sync-progress.latest.json',
      progressFound: true,
      progressReadable: true,
      progressUpdatedAt: '2026-04-29T06:54:18Z',
      progressHeartbeatAt: '2026-04-29T06:54:18Z',
      progressHeartbeatAgeMs: 120000,
      progressStale: false,
      progressKind: 'live',
      updatedAt: '2026-04-29T06:54:18Z',
    },
    {
      id: 'buff-page-immunity-refresh',
      label: 'Buff immunity page refresh',
      status: 'stalled',
      priority: 'p0',
      lane: 'fetch',
      queueState: 'running payload heartbeat is stale',
      current: 50,
      total: 388,
      progressPath: 'data/generated/fetch-wiki-buffs-progress.latest.json',
      progressSource: 'data/generated/fetch-wiki-buffs-progress.latest.json',
      progressFound: true,
      progressReadable: true,
      progressHeartbeatAt: '2026-04-29T06:00:00Z',
      progressHeartbeatAgeMs: 1801000,
      progressStale: true,
      progressStaleReason: 'running progress heartbeat is older than 10 minutes',
      progressKind: 'stalled',
    },
    {
      id: 'domain-source-bosses',
      label: 'Domain source: Bosses',
      status: 'running',
      priority: 'p0',
      lane: 'fetch',
      queueState: 'fetched boss source snapshots 7/14',
      nextStep: 'Review boss source snapshot evidence.',
      dataStage: 'wiki domain source pages -> generated source snapshot',
      current: 7,
      total: 14,
      percent: 50,
      outputPath: 'data/generated/wiki-bosses.latest.json',
      reportPath: 'reports/domain/domain-source-bosses-2026-05-24.json',
      progressPath: 'data/generated/domain-source-bosses-progress.latest.json',
      progressSource: 'data/generated/domain-source-bosses-progress.latest.json',
      progressFound: true,
      progressReadable: true,
      progressHeartbeatAt: '2026-05-24T01:00:00Z',
      progressHeartbeatAgeMs: 120000,
      progressStale: false,
      progressKind: 'live',
    },
    {
      id: 'domain-source-armor-sets',
      label: 'Domain source: Armor sets',
      status: 'missing',
      priority: 'p0',
      lane: 'fetch',
      queueState: 'progress file missing',
      nextStep: 'Run the domain source snapshot fetch before downstream audit evidence.',
      dataStage: 'wiki domain source pages -> generated source snapshot',
      outputPath: 'data/generated/wiki-armor-sets.latest.json',
      progressPath: 'data/generated/domain-source-armor-sets-progress.latest.json',
      progressSource: 'data/generated/domain-source-armor-sets-progress.latest.json',
      progressFound: false,
      progressReadable: false,
      progressKind: 'missing',
    },
    {
      id: 'domain-source-shimmer',
      label: 'Domain source: Shimmer',
      status: 'missing',
      priority: 'p0',
      lane: 'fetch',
      queueState: 'progress file missing',
      nextStep: 'Run the domain source snapshot fetch before downstream audit evidence.',
      dataStage: 'wiki domain source pages -> generated source snapshot',
      outputPath: 'data/generated/shimmer/wiki-shimmer-manifest.latest.json',
      progressPath: 'data/generated/domain-source-shimmer-progress.latest.json',
      progressSource: 'data/generated/domain-source-shimmer-progress.latest.json',
      progressFound: false,
      progressReadable: false,
      progressKind: 'missing',
    },
    {
      id: 'domain-source-town-npc-maintenance',
      label: 'Domain source: Town NPC maintenance',
      status: 'missing',
      priority: 'p0',
      lane: 'fetch',
      queueState: 'progress file missing',
      nextStep: 'Run the domain source snapshot fetch before downstream audit evidence.',
      dataStage: 'wiki domain source pages -> generated source snapshot',
      outputPath: 'data/generated/wiki-town-npc-maintenance.latest.json',
      progressPath: 'data/generated/domain-source-town-npc-maintenance-progress.latest.json',
      progressSource: 'data/generated/domain-source-town-npc-maintenance-progress.latest.json',
      progressFound: false,
      progressReadable: false,
      progressKind: 'missing',
    },
  ],
}

void overview

const reportDetail: CrawlerMonitorReportDetail = {
  found: true,
  readable: true,
  name: 'relation-health-smoke.json',
  path: 'reports/relation/relation-health-smoke.json',
  category: 'audit',
  updatedAt: '2026-04-29T08:00:00Z',
  sizeBytes: 128,
  contentType: 'json',
  content: '{\n  "status" : "ok"\n}',
  truncated: false,
  maxBytes: 200000,
}

void reportDetail

const testState: CrawlerMonitorTestState = {
  generatedAt: '2026-04-28T00:00:00Z',
  path: 'reports/backend-refresh/manual-monitor-test.json',
  found: true,
  readable: true,
  payload: {
    scenario: 'running',
    daemonStatus: 'running',
    schedulerStatus: 'sleeping',
    lockFound: false,
    latestRun: {
      totalActions: 2,
      completedActions: 1,
      runningActions: 1,
    },
  },
  overview: {
    refreshStale: false,
    daemon: {
      found: true,
      readable: true,
      path: 'reports/backend-refresh/backend-refresh-daemon.heartbeat.json',
      payload: {
        status: 'idle',
      },
    },
    scheduler: {
      found: true,
      readable: true,
      path: 'reports/backend-refresh/backend-refresh-scheduler-state.json',
      payload: {
        status: 'sleeping',
      },
    },
    lock: {
      found: false,
      readable: false,
      path: 'reports/backend-refresh/backend-refresh.lock',
    },
    latestRun: {
      found: true,
      readable: true,
      totalActions: 2,
      completedActions: 1,
      runningActions: 1,
      actions: [
        {
          id: 'wiki-refresh',
          runner: 'node',
          status: 'running',
          current: 3,
          total: 8,
          startedAt: '2026-04-29T00:00:00Z',
          batchOffset: 0,
          batchLimit: 100,
          overallCurrent: 3,
          overallTotal: 6131,
          percent: 37.5,
          phase: 'apply',
          message: 'running standalone wiki sync action 3 of 8',
          lastHeartbeatAt: '2026-04-29T00:00:30Z',
          childStatusPath: 'data/generated/wiki-sync-progress.latest.json',
          durationMs: 1200,
        },
      ],
    },
  },
}

void testState
