import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dirname, '..')

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8').replace(/\r\n/g, '\n').replace(/\r/g, '\n')
}

const page = read('pages/article-comments.vue')
const store = read('stores/articleComments.ts')
const layout = read('layouts/default.vue')

test('single article comment management page defaults to article list entry', () => {
  assert.match(page, /class="page-wrap page-workspace article-comments-page"/)
  assert.match(page, /class="workspace-shell workspace-shell--unified section-card article-comments-command-bar article-list-command-bar"/)
  assert.match(page, /definePageMeta\(\{[\s\S]*title:\s*'评论管理'/)
  assert.match(page, /文章评论管理/)
  assert.match(page, /useArticlesStore\(\)/)
  assert.match(page, /articleRows/)
  assert.match(page, /articleKeyword/)
  assert.match(page, /articleListSortBy/)
  assert.match(page, /articleListSortOrder/)
  assert.match(page, /handleArticleListSearch/)
  assert.doesNotMatch(page, /refreshVisibleArticleCommentCounts/)
  assert.match(page, /openArticleCommentWorkspace\(row\)/)
  assert.match(page, /backToArticleList/)
  assert.match(page, /article-entry-list/)
  assert.match(page, /article-entry-row/)
  assert.match(page, /article-entry-cover/)
  assert.match(page, /article-entry-meta/)
  assert.match(page, /article-entry-signals/)
  assert.match(page, /article-entry-action-bar/)
  assert.match(page, /row\.coverImage/)
  assert.match(page, /articleAuthorLabel\(row\)/)
  assert.match(page, /formatCount\(row\.commentCount\)/)
  assert.match(page, /评论数/)
  assert.match(page, /浏览数/)
  assert.match(page, /更新时间/)
  assert.match(page, /文章 ID/)
  assert.match(page, /降序/)
  assert.match(page, /升序/)
  assert.match(page, /管理评论/)
  assert.doesNotMatch(page, /articleSearchInput/)
  assert.doesNotMatch(page, /loadArticleForModeration/)
})

test('article list store preserves quick location fields for comment management', () => {
  const articlesStore = read('stores/articles.ts')
  assert.match(articlesStore, /authorId\?: number/)
  assert.match(articlesStore, /authorDisplayName\?: string/)
  assert.match(articlesStore, /authorAvatarUrl\?: string/)
  assert.match(articlesStore, /commentCount\?: number/)
  assert.match(articlesStore, /viewCount\?: number/)
  assert.match(articlesStore, /likeCount\?: number/)
  assert.match(articlesStore, /authorId: item\?\.authorId/)
  assert.match(articlesStore, /authorDisplayName: item\?\.authorDisplayName/)
  assert.match(articlesStore, /authorAvatarUrl: item\?\.authorAvatarUrl/)
  assert.match(articlesStore, /commentCount: item\?\.commentCount == null \? undefined : Number\(item\.commentCount\)/)
  assert.match(articlesStore, /export type AdminArticleListSortBy = 'commentCount' \| 'viewCount' \| 'updatedAt' \| 'id'/)
  assert.match(articlesStore, /export type AdminArticleListSortOrder = 'desc' \| 'asc'/)
  assert.match(articlesStore, /const sortBy = ref<AdminArticleListSortBy>\('commentCount'\)/)
  assert.match(articlesStore, /const sortOrder = ref<AdminArticleListSortOrder>\('desc'\)/)
  assert.match(articlesStore, /sortBy:\s*sortBy\.value/)
  assert.match(articlesStore, /sortOrder:\s*sortOrder\.value/)
  assert.doesNotMatch(articlesStore, /extractArticleCommentCount/)
  assert.doesNotMatch(articlesStore, /refreshArticleCommentCounts/)
  assert.doesNotMatch(articlesStore, /fetchArticleCommentTotal/)
  assert.match(articlesStore, /raw\?\.data\?\.pagination/)
  assert.match(articlesStore, /raw\?\.data\?\.page/)
  assert.match(articlesStore, /raw\?\.data\?\.total/)
})

test('single article comment management page exposes B-version workspace controls', () => {
  assert.match(page, /class="workspace-shell workspace-shell--unified section-card article-comments-command-bar"/)
  assert.match(page, /单文章评论区管理/)
  assert.match(page, /currentArticle/)
  assert.match(page, /commentFilters\.keyword/)
  assert.match(page, /commentFilters\.status/)
  assert.match(page, /commentFilters\.authorId/)
  assert.match(page, /commentFilters\.sortBy/)
  assert.match(page, /commentFilters\.sortOrder/)
  assert.match(page, /搜索评论内容或作者/)
  assert.match(page, /回复量/)
  assert.match(page, /点赞数/)
  assert.match(page, /创建时间/)
  assert.match(page, /评论 ID/)
  assert.match(page, /降序/)
  assert.match(page, /升序/)
  assert.doesNotMatch(page, /commentFilters\.sortMode/)
  assert.doesNotMatch(page, /commentFilters\.articleId/)
  assert.doesNotMatch(page, /全站文章评论巡检/)
})

test('single article comment management page renders dense table and full detail view', () => {
  assert.match(page, /class="comment-moderation-workspace"/)
  assert.match(page, /class="[^"]*comment-list-inspector/)
  assert.match(page, /selectedCommentSummary/)
  assert.match(page, /commentIdentityLabel/)
  assert.match(page, /commentReplyTargetLabel/)
  assert.match(page, /commentRelationLine/)
  assert.match(page, /activeCommentView/)
  assert.match(page, /commentListView/)
  assert.match(page, /openCommentDetail\(row\)/)
  assert.match(page, /returnToCommentList/)
  assert.match(page, /class="[^"]*dense-comments-table/)
  assert.match(page, /<colgroup>/)
  assert.match(page, /class="col-id"/)
  assert.match(page, /<th>ID<\/th>/)
  assert.match(page, /<th>评论内容<\/th>/)
  assert.match(page, /comment-content-cell/)
  assert.match(page, /<th>作者<\/th>/)
  assert.match(page, /<th>状态<\/th>/)
  assert.match(page, /<th>互动<\/th>/)
  assert.match(page, /<th>创建时间<\/th>/)
  assert.match(page, /<th>操作<\/th>/)
  assert.match(page, /selectedComment/)
  assert.match(page, /class="[^"]*comment-detail-view/)
  assert.match(page, /class="[^"]*comment-detail-layout/)
  assert.match(page, /class="[^"]*comment-relation-grid/)
  assert.match(page, /class="[^"]*comment-detail-primary/)
  assert.match(page, /class="[^"]*comment-detail-side/)
  assert.match(page, /评论详情/)
  assert.match(page, /返回评论列表/)
  assert.match(page, /关系结构/)
  assert.match(page, /关系速览/)
  assert.match(page, /文章作者/)
  assert.match(page, /用户/)
  assert.match(page, /评论主体/)
  assert.match(page, /管理操作/)
  assert.match(page, /回复链/)
  assert.match(page, /detailReplyRows/)
  assert.doesNotMatch(page, /comment-detail-drawer/)
  assert.doesNotMatch(page, /empty-state--drawer/)
  assert.doesNotMatch(page, /comment-row--reply/)
})

test('single article comment management page avoids a narrow table with empty right side', () => {
  assert.match(page, /\.comment-moderation-workspace\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*320px/)
  assert.match(page, /\.dense-comments-table\s*\{[\s\S]*width:\s*100%/)
  assert.match(page, /\.comment-list-inspector\s*\{[\s\S]*position:\s*sticky/)
  assert.match(page, /@mouseenter="previewComment\(row\)"/)
  assert.match(page, /class="[^"]*comment-inspector-relation/)
})

test('single article comment management page keeps return path in empty comment state', () => {
  assert.match(page, /empty-comments-state/)
  assert.match(page, /这篇文章暂无评论/)
  assert.match(page, /回到文章列表/)
  assert.match(page, /@click="backToArticleList"/)
  assert.match(page, /returnToCommentList/)
})

test('single article comment management page enforces moderation action rules in detail view', () => {
  assert.match(page, /moderationTargetComment/)
  assert.match(page, /setModerationTarget\(reply\)/)
  assert.match(page, /setModerationTarget\(selectedComment\)/)
  assert.match(page, /当前处理对象/)
  assert.match(page, /处理此条/)
  assert.match(page, /目标评论/)
  assert.match(page, /moderationReasonPresets/)
  assert.match(page, /selectedReasonPreset/)
  assert.match(page, /applyModerationReasonPreset/)
  assert.match(page, /快捷处理原因/)
  assert.match(page, /请选择预设原因/)
  assert.match(page, /广告引流/)
  assert.match(page, /人身攻击/)
  assert.match(page, /const canHideComment = \(comment: GlobalArticleComment \| null\)/)
  assert.match(page, /comment\?\.status === 'PUBLISHED'/)
  assert.match(page, /const canRestoreComment = \(comment: GlobalArticleComment \| null\)/)
  assert.match(page, /comment\?\.status === 'HIDDEN' \|\| comment\?\.status === 'DELETED'/)
  assert.match(page, /const canDeleteComment = \(comment: GlobalArticleComment \| null\)/)
  assert.match(page, /comment\?\.status !== 'DELETED' && comment\?\.status !== 'UNKNOWN'/)
  assert.match(page, /submitStatusChange\('HIDDEN'\)/)
  assert.match(page, /submitStatusChange\('PUBLISHED'\)/)
  assert.match(page, /submitStatusChange\('DELETED'\)/)
  assert.match(page, /const targetId = moderationTargetComment\.value\.id/)
  assert.doesNotMatch(page, /const targetId = selectedComment\.value\.id/)
  assert.match(page, /请输入处理原因/)
  assert.match(page, /statusReason\.value = selectedReasonPreset\.value/)
})

test('single article comment store only uses existing article-scoped backend endpoints', () => {
  assert.match(store, /export interface ManagedArticleSummary/)
  assert.match(store, /export type ArticleCommentSortBy = 'replyCount' \| 'createdAt' \| 'likeCount' \| 'id'/)
  assert.match(store, /export type ArticleCommentSortOrder = 'desc' \| 'asc'/)
  assert.match(store, /sortBy: ArticleCommentSortBy/)
  assert.match(store, /sortOrder: ArticleCommentSortOrder/)
  assert.match(store, /replyCount/)
  assert.match(store, /const currentArticle = ref<ManagedArticleSummary \| null>\(null\)/)
  assert.match(store, /const fetchArticleById = async \(articleId: number\)/)
  assert.match(store, /get\(`\/admin\/articles\/\$\{articleId\}`\)/)
  assert.match(store, /const fetchComments = async \(page = pagination\.value\.page, size = pagination\.value\.size\)/)
  assert.match(store, /get\(`\/admin\/articles\/\$\{article\.id\}\/comments`/)
  assert.match(store, /const fetchCommentReplies = async \(commentId: number, page = 1, size = 20\)/)
  assert.match(store, /get\(`\/admin\/articles\/\$\{article\.id\}\/comments\/\$\{commentId\}\/replies`/)
  assert.match(store, /patch\(`\/admin\/articles\/\$\{article\.id\}\/comments\/\$\{commentId\}\/status`/)
  assert.match(store, /keyword:\s*filters\.value\.keyword/)
  assert.match(store, /authorId:\s*filters\.value\.authorId/)
  assert.match(store, /status:\s*filters\.value\.status/)
  assert.match(store, /sortBy:\s*filters\.value\.sortBy/)
  assert.match(store, /sortOrder:\s*filters\.value\.sortOrder/)
  assert.doesNotMatch(store, /const sortComments/)
  assert.doesNotMatch(store, /comments\.value = sortComments/)
  assert.doesNotMatch(store, /\/admin\/article-comments/)
  assert.doesNotMatch(store, /demoCommentFixtures/)
  assert.doesNotMatch(store, /demoMode/)
  assert.doesNotMatch(store, /articleScopedMode/)
  assert.doesNotMatch(store, /fetchArticleScopedComments/)
})

test('single article comment store preserves scoped article comment store boundaries', () => {
  const articlesStore = read('stores/articles.ts')
  assert.match(articlesStore, /`\/admin\/articles\/\$\{articleId\}\/comments`/)
  assert.match(articlesStore, /`\/admin\/articles\/\$\{articleId\}\/comments\/\$\{commentId\}\/replies`/)
  assert.match(articlesStore, /`\/admin\/articles\/\$\{articleId\}\/comments\/\$\{commentId\}\/status`/)
})

test('sidebar exposes single article comment management under operations', () => {
  assert.match(layout, /MessageSquareText/)
  assert.match(layout, /name:\s*'评论管理'/)
  assert.match(layout, /path:\s*'\/article-comments'/)
  assert.match(layout, /hint:\s*'单文章评论区审核'/)
})
