import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(import.meta.dirname, '..')

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8').replace(/\r\n/g, '\n').replace(/\r/g, '\n')
}

function readIfExists(relativePath) {
  const fullPath = path.join(repoRoot, relativePath)
  return fs.existsSync(fullPath) ? fs.readFileSync(fullPath, 'utf8').replace(/\r\n/g, '\n').replace(/\r/g, '\n') : ''
}

const page = read('pages/articles.vue')
const editorWorkspace = read('components/article/ArticleEditorWorkspace.vue')
const articleReviewWorkspace = readIfExists('components/article/ArticleReviewWorkspace.vue')
const articleEditorNewPage = read('pages/article-editor/new.vue')
const articleEditorDetailPage = read('pages/article-editor/[id].vue')
const articlesStore = read('stores/articles.ts')
const articleEditor = read('utils/articleEditor.ts')
const nuxtConfig = read('nuxt.config.ts')
const articleEditorComposable = read('composables/useArticleEditor.ts')

test('admin articles page exposes content preview from article detail', () => {
  assert.match(page, /@click="openContentPreview\(row\)"/)
  assert.match(page, />\s*查看正文\s*</)
  assert.match(page, /articlesStore\.fetchArticleById\(row\.id\)/)
  assert.match(page, /contentPreviewVisible/)
  assert.match(page, /contentPreviewLoading/)
  assert.match(page, /contentPreviewArticle/)
  assert.match(page, /contentPreviewHtml/)
  assert.match(page, /contentHtml/)
  assert.match(page, /contentMarkdown/)
  assert.match(page, /sanitizeArticleHtml/)
  assert.match(page, /article-content-preview/)
  assert.match(page, /content-preview-rich/)
})

test('admin articles page keeps review operations and pending rows editor-accessible', () => {
  assert.doesNotMatch(page, /:disabled="row\.reviewStatus === 'PENDING_REVIEW'"/)
  assert.match(page, /editorActionLabel\(row\)/)
  assert.match(page, /row\.reviewStatus === 'PENDING_REVIEW'\s*\?\s*'审核文章'\s*:\s*'继续写作'/)
  assert.doesNotMatch(page, /只读编辑器/)
  assert.match(page, /canSubmitReview\(row\)/)
  assert.match(page, /canPublish\(row\)/)
  assert.match(page, /canOffline\(row\)/)
  assert.match(page, /openReviewLogs\(row\)/)
})

test('admin articles page does not bypass the review workbench for pending articles', () => {
  assert.doesNotMatch(page, /@click="approveReview\(row\)"/)
  assert.doesNotMatch(page, /@click="openReject\(row\)"/)
  assert.doesNotMatch(page, /const approveReview = async/)
  assert.doesNotMatch(page, /const rejectReview = async/)
  assert.doesNotMatch(page, /articlesStore\.reviewArticle\(row\.id/)
  assert.doesNotMatch(page, /title="驳回文章审核"/)
  assert.match(page, /待审核文章请进入审核工作台处理/)
})

test('admin articles page labels offline action as unpublish', () => {
  assert.match(page, /isActionLoading\(row\.id,\s*'offline'\)\s*\?\s*'取消发布中\.\.\.'\s*:\s*'取消发布'/)
  assert.doesNotMatch(page, /Offlining\.\.\./)
  assert.doesNotMatch(page, /isActionLoading\(row\.id,\s*'offline'\)\s*\?\s*'Offlining\.\.\.'\s*:\s*'Offline'/)
})

test('admin articles page renders cover thumbnails from normalized image urls', () => {
  assert.match(page, /<th>封面<\/th>/)
  assert.match(page, /v-if="row\.coverImage"/)
  assert.match(page, /:src="row\.coverImage"/)
  assert.match(page, /class="article-cover-thumb"/)
  assert.match(page, /@error="handleCoverImageError"/)
})

test('admin articles page uses a compact operations layout instead of broad explainer cards', () => {
  assert.match(page, /class="[^"]*articles-command-bar[^"]*"/)
  assert.match(page, /class="articles-count"/)
  assert.match(page, /<th>文章<\/th>/)
  assert.match(page, /<th>状态<\/th>/)
  assert.match(page, /<th>时间线<\/th>/)
  assert.match(page, /class="article-state-stack"/)
  assert.match(page, /class="article-timeline"/)
  assert.match(page, /class="[^"]*actions-group--primary[^"]*"/)
  assert.match(page, /class="[^"]*actions-group--workflow[^"]*"/)
  assert.doesNotMatch(page, /class="section-card overview-grid"/)
  assert.doesNotMatch(page, /<th>Submitted<\/th>/)
  assert.doesNotMatch(page, /<th>Published<\/th>/)
  assert.doesNotMatch(page, /<th>Updated<\/th>/)
})

test('admin articles content preview renders sanitized rich html so inline images remain visible', () => {
  assert.match(page, /import \{ sanitizeArticleHtml \} from '~\/utils\/articleEditor'/)
  assert.match(page, /contentPreviewHtml/)
  assert.match(page, /v-html="contentPreviewHtml"/)
  assert.match(page, /class="content-preview-rich"/)
  assert.match(page, /\.content-preview-rich :deep\(img\)/)
  assert.match(page, /\.content-preview-rich :deep\(\.tp-content-ref\)/)
  assert.match(page, /width: 1\.875em/)
  assert.doesNotMatch(page, /<pre v-else-if="contentPreviewText"/)
  assert.doesNotMatch(page, /stripArticleContentMarkup/)
  assert.match(articleEditor, /next\.startsWith\('\/terrapedia-images\/'\)/)
  assert.match(articleEditor, /data-tp-ref-display/)
  assert.match(articleEditor, /isSafeContentReferenceImageUrl/)
  assert.match(articleEditor, /setAttribute\('class', 'tp-content-ref'\)/)
  assert.match(articleEditor, /tp-content-ref-fallback/)
})

test('admin article editor preview renders content references like the public article renderer', () => {
  assert.match(editorWorkspace, /\.article-preview__body :deep\(\.tp-content-ref\)/)
  assert.match(editorWorkspace, /width: 1\.875em/)
  assert.match(editorWorkspace, /\.article-preview__body :deep\(\.tp-content-ref\[data-tp-ref-display="text"\]\)/)
  assert.match(editorWorkspace, /\.article-preview__body :deep\(\.tp-content-ref-fallback\)/)
})

test('admin article editor opens content references in the side inspector while staying in writing mode', () => {
  assert.match(editorWorkspace, /class="[^"]*toolbar-tool--reference[^"]*"/)
  assert.match(editorWorkspace, /@click="editor\.openReferencePanel"/)
  assert.match(editorWorkspace, /document-inspector__references/)
  assert.match(editorWorkspace, /v-if="editor\.referencePanelOpen"/)
  assert.match(editorWorkspace, /editor\.referenceSearchResults/)
  assert.match(editorWorkspace, /editor\.insertContentReference\(reference\)/)
  assert.match(editorWorkspace, /item\.id === 'references' \? editor\.openReferencePanel\(\) : editor\.setSidePanel\(item\.id\)/)
  assert.match(editorWorkspace, /@mousedown\.prevent="item\.id === 'references' \? editor\.saveSelection\(\) : undefined"/)
  assert.match(editorWorkspace, /:disabled="item\.id === 'references' && editor\.isReadOnly"/)
  assert.match(editorWorkspace, /@mousedown\.prevent/)
  assert.match(editorWorkspace, /:disabled="editor\.isReadOnly \|\| editor\.referenceSearchLoading"/)
  assert.doesNotMatch(editorWorkspace, /class="user-rich-editor__insert-bar"/)
  assert.doesNotMatch(editorWorkspace, /class="user-rich-editor__reference-popover"/)
  assert.match(articleEditorComposable, /type EditorPanel = 'preview' \| 'outline' \| 'quality' \| 'references'/)
  assert.match(articleEditorComposable, /const referencePanelOpen = ref\(false\)/)
  assert.match(articleEditorComposable, /const setSidePanel = \(panel: EditorPanel\) => \{[\s\S]*if \(panel === 'references' && isReadOnly\.value\) return[\s\S]*sidePanel\.value = panel/)
  assert.match(articleEditorComposable, /const openReferencePanel = \(\) => \{[\s\S]*if \(isReadOnly\.value\) return[\s\S]*saveSelection\(\)[\s\S]*sidePanelCollapsed\.value = false[\s\S]*setSidePanel\('references'\)/)
  assert.match(articleEditorComposable, /searchArticleContentReferences/)
  assert.match(articleEditorComposable, /insertContentReference/)
  assert.match(articleEditorComposable, /if \(isReadOnly\.value\) return/)
  assert.match(articleEditorComposable, /normalizeArticleContentReference/)
  assert.match(articleEditorComposable, /buildContentReferenceHtml/)
  assert.match(articleEditorComposable, /Array\.isArray\(response\?\.data\)/)
  assert.match(articleEditorComposable, /SUPPORTED_REFERENCE_TYPES: ContentReferenceType\[] = \['item', 'npc', 'boss'\]/)
  assert.match(articleEditorComposable, /label\.length > MAX_REFERENCE_LABEL_LENGTH/)
  assert.match(articleEditorComposable, /isSafeReferenceImageUrl/)
  assert.match(articleEditorComposable, /encodeAttributeValue\(normalized\.label\)/)
  assert.match(articleEditorComposable, /escapeHtml\(normalized\.label\)/)
  assert.doesNotMatch(articleEditorComposable, /data-tp-href/)
  assert.doesNotMatch(articleEditorComposable, /onclick|onmouseenter|onfocus/)
  assert.match(articleEditorComposable, /insertHtmlAtCaret\(html\)/)
  assert.match(articleEditor, /span: new Set\(\[[^\]]*'contenteditable'[^\]]*\]\)/)
  assert.match(articleEditor, /setAttribute\('contenteditable', 'false'\)/)
  assert.match(articleEditor, /classes\.includes\('tp-content-ref-fallback'\)[\s\S]*element\.removeAttribute\('contenteditable'\)/)
  assert.match(articleEditor, /element\.removeAttribute\('contenteditable'\)/)
  assert.doesNotMatch(articleEditorComposable, /reviewMode/)
  assert.doesNotMatch(articleEditorComposable, /router\.push\([^)]*reference/)
  assert.match(articleEditorDetailPage, /reviewMode\.value\s*=\s*article\.value\?\.reviewStatus\s*===\s*'PENDING_REVIEW'/)
})

test('admin article editor uses a focused detail workspace layout without garbled toolbar copy', () => {
  assert.match(editorWorkspace, /class="editor-workbar"/)
  assert.match(editorWorkspace, /class="editor-workbar__identity"/)
  assert.match(editorWorkspace, /class="editor-workbar__metrics"/)
  assert.match(editorWorkspace, /class="editor-workbar__actions"/)
  assert.match(editorWorkspace, /class="[^"]*document-first-workspace[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-editor-surface[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-paper-rail[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-title-panel[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-toolbar-band[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-toolbar-actions[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-writing-stage[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-inspector__setup[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-inspector__cover[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-inspector__quality[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*document-inspector__tools[^"]*"/)
  assert.match(editorWorkspace, /\.document-editor-surface\s*\{/)
  assert.match(editorWorkspace, /\.document-paper-rail\s*\{/)
  assert.match(editorWorkspace, /\.document-toolbar-band\s*\{/)
  assert.match(editorWorkspace, /\.document-toolbar-actions\s*\{/)
  assert.match(editorWorkspace, /\.document-writing-stage\s*\{/)
  assert.match(editorWorkspace, /\.document-inspector__quality\s*\.checklist\s*\{/)
  assert.match(editorWorkspace, /\.document-inspector__tools\s*\{/)
  assert.match(editorWorkspace, /grid-template-columns:\s*minmax\(0,\s*1fr\)\s+340px/)
  assert.match(editorWorkspace, /class="[^"]*setup-ready-summary[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*quality-panel__checklist[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*editor-card--writing[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*inspector-panel[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*toolbar-group--common[^"]*"/)
  assert.match(editorWorkspace, /class="[^"]*editor-page--readable[^"]*"/)
  assert.match(editorWorkspace, /--editor-paper:\s*var\(--color-surface-2\)/)
  assert.match(editorWorkspace, /--editor-ink:\s*var\(--color-text\)/)
  assert.doesNotMatch(editorWorkspace, /閺傚洤鐡/)
  assert.doesNotMatch(editorWorkspace, /class="editor-shell__meta"/)
  assert.doesNotMatch(editorWorkspace, /setup-strip__checklist/)
  assert.doesNotMatch(editorWorkspace, /editor-setup-strip/)
  assert.doesNotMatch(editorWorkspace, /compact-setup-bar/)
  assert.doesNotMatch(editorWorkspace, /class="cover-dropzone"/)
  assert.doesNotMatch(editorWorkspace, /toolbar-group--advanced/)
  assert.doesNotMatch(editorWorkspace, /toolbar-group--more/)
  assert.doesNotMatch(editorWorkspace, /toolbarOverflowOpen/)
  assert.doesNotMatch(editorWorkspace, /grid-template-columns:\s*320px minmax\(0,\s*1fr\) 360px/)
  assert.doesNotMatch(editorWorkspace, /color-mix\(in srgb, var\(--color-bg(?:-secondary)?\)[^)]*black/)
})

test('admin article editor and review workspace inherit global theme colors', () => {
  assert.match(editorWorkspace, /--editor-paper:\s*var\(--color-surface-2\)/)
  assert.match(editorWorkspace, /--editor-paper-soft:\s*color-mix\(in srgb, var\(--color-bg-secondary\)/)
  assert.match(editorWorkspace, /--editor-rail:\s*color-mix\(in srgb, var\(--color-bg-tertiary\)/)
  assert.match(editorWorkspace, /--editor-ink:\s*var\(--color-text\)/)
  assert.match(editorWorkspace, /--editor-ink-muted:\s*var\(--color-text-secondary\)/)
  assert.match(editorWorkspace, /--editor-border:\s*color-mix\(in srgb, var\(--color-border\)/)
  assert.match(editorWorkspace, /--editor-accent:\s*var\(--color-primary\)/)
  assert.match(editorWorkspace, /--editor-warning-soft:\s*color-mix\(in srgb, var\(--color-warning\)/)
  assert.match(editorWorkspace, /--editor-danger-soft:\s*color-mix\(in srgb, var\(--color-danger\)/)
  assert.doesNotMatch(editorWorkspace, /--editor-paper:\s*#/)
  assert.doesNotMatch(editorWorkspace, /--editor-ink:\s*#/)
  assert.doesNotMatch(editorWorkspace, /background:\s*rgba\(255,\s*255,\s*255/)
  assert.doesNotMatch(editorWorkspace, /color:\s*#fff/)

  assert.match(articleReviewWorkspace, /--review-bg:\s*color-mix\(in srgb, var\(--color-bg-tertiary\)/)
  assert.match(articleReviewWorkspace, /--review-surface:\s*var\(--color-surface-2\)/)
  assert.match(articleReviewWorkspace, /--review-surface-muted:\s*color-mix\(in srgb, var\(--color-bg-secondary\)/)
  assert.match(articleReviewWorkspace, /--review-ink:\s*var\(--color-text\)/)
  assert.match(articleReviewWorkspace, /--review-muted:\s*var\(--color-text-secondary\)/)
  assert.match(articleReviewWorkspace, /--review-border:\s*color-mix\(in srgb, var\(--color-border\)/)
  assert.match(articleReviewWorkspace, /--review-accent:\s*var\(--color-primary\)/)
  assert.match(articleReviewWorkspace, /--review-danger:\s*var\(--color-danger\)/)
  assert.match(articleReviewWorkspace, /--review-danger-soft:\s*color-mix\(in srgb, var\(--color-danger\)/)
  assert.doesNotMatch(articleReviewWorkspace, /--review-surface:\s*#/)
  assert.doesNotMatch(articleReviewWorkspace, /--review-ink:\s*#/)
  assert.doesNotMatch(articleReviewWorkspace, /background:\s*rgba\(255,\s*255,\s*255/)
  assert.doesNotMatch(articleReviewWorkspace, /color:\s*#fff/)
})

test('admin article editor routes keep a single element root for Nuxt page transitions', () => {
  assert.match(articleEditorNewPage, /<template>\s*<div class="page-wrap page-workspace article-editor-route">\s*<ClientOnly>/)
  assert.match(articleEditorNewPage, /<\/ClientOnly>\s*<\/div>\s*<\/template>/)
  assert.match(articleEditorDetailPage, /<template>\s*<div class="page-wrap page-workspace article-editor-route">\s*<ClientOnly>/)
  assert.match(articleEditorDetailPage, /<\/ClientOnly>\s*<\/div>\s*<\/template>/)
})

test('admin pending article detail route uses the review workbench before the editor', () => {
  assert.match(articleEditorDetailPage, /ArticleReviewWorkspace/)
  assert.match(articleEditorDetailPage, /ArticleEditorWorkspace/)
  assert.match(articleEditorDetailPage, /reviewStatus\s*===\s*'PENDING_REVIEW'/)
  assert.match(articleEditorDetailPage, /articlesStore\.fetchArticleById\(articleId\.value\)/)
  assert.match(articleEditorDetailPage, /watch\(articleId,\s*\(\)\s*=>\s*\{/)
  assert.match(articleEditorDetailPage, /reviewMode\.value\s*=\s*article\.value\?\.reviewStatus\s*===\s*'PENDING_REVIEW'/)
  assert.match(articleEditorDetailPage, /@reviewed="handleArticleReviewed"/)
})

test('admin article review workbench keeps review as the primary task', () => {
  assert.match(articleReviewWorkspace, /class="article-review-workspace"/)
  assert.match(articleReviewWorkspace, /读者预览/)
  assert.match(articleReviewWorkspace, /审核检查/)
  assert.match(articleReviewWorkspace, /问题位置/)
  assert.match(articleReviewWorkspace, /问题类型/)
  assert.match(articleReviewWorkspace, /打回说明/)
  assert.match(articleReviewWorkspace, /通过审核/)
  assert.match(articleReviewWorkspace, /打回修改/)
  assert.match(articleReviewWorkspace, /reviewArticle\(article\.value\.id,\s*'APPROVE'/)
  assert.match(articleReviewWorkspace, /reviewArticle\(article\.value\.id,\s*'REJECT'/)
  assert.match(articleReviewWorkspace, /fetchReviewLogs\(article\.value\.id/)
  assert.match(articleReviewWorkspace, /sanitizeArticleHtml/)
  assert.match(articleReviewWorkspace, /buildArticlePresentation/)
  assert.doesNotMatch(articleReviewWorkspace, /contenteditable=/)
})

test('admin article review workbench only enables review actions for pending articles', () => {
  assert.match(articleReviewWorkspace, /canReviewCurrent/)
  assert.match(articleReviewWorkspace, /article\.value\?\.reviewStatus\s*===\s*'PENDING_REVIEW'/)
  assert.match(articleReviewWorkspace, /:disabled="reviewing \|\| !canReviewCurrent"/)
  assert.match(articleReviewWorkspace, /当前状态不是待审核/)
  assert.match(articleReviewWorkspace, /watch\(\(\)\s*=>\s*props\.articleId/)
  assert.match(articleReviewWorkspace, /defineEmits/)
  assert.match(articleReviewWorkspace, /emit\('reviewed',\s*article\.value\)/)
  assert.match(articleReviewWorkspace, /initialArticle/)
})

test('admin article editor pre-bundles client-only editor dependencies', () => {
  assert.match(nuxtConfig, /vite:\s*\{[\s\S]*optimizeDeps:\s*\{[\s\S]*include:\s*\[[^\]]*'@vueuse\/core'[^\]]*'lucide-vue-next'[^\]]*\]/)
})

test('admin article editor toolbar preserves native select interactions', () => {
  assert.match(editorWorkspace, /@mousedown="editor\.handleToolbarMouseDown"/)
  assert.doesNotMatch(editorWorkspace, /@mousedown\.prevent="editor\.handleToolbarMouseDown"/)
})

test('admin article editor normalizes selected font size to explicit pixels', () => {
  assert.match(articleEditorComposable, /fontSize\s*===\s*'xxx-large'/)
  assert.match(articleEditorComposable, /style\.fontSize\s*=\s*`\$\{targetPx\}px`/)
})

test('admin article editor exposes cover crop and zoom controls', () => {
  assert.match(editorWorkspace, /裁剪\/放大封面/)
  assert.match(editorWorkspace, /v-model="editor\.cropVisible"/)
  assert.match(editorWorkspace, /v-model\.number="editor\.cropScale"/)
  assert.match(articleEditorComposable, /const renderCroppedBlob/)
  assert.match(articleEditorComposable, /const confirmCrop/)
})

test('admin article store normalizes article image urls through the admin origin proxy', () => {
  assert.match(articlesStore, /export const normalizeAdminArticleImageUrl/)
  assert.match(articlesStore, /raw\.startsWith\('\/preview-assets\/terrapedia-images\/'\)/)
  assert.match(articlesStore, /url\.pathname\.startsWith\('\/terrapedia-images\/'\)/)
  assert.match(articlesStore, /return `\$\{url\.pathname\}\$\{url\.search\}\$\{url\.hash\}`/)
  assert.match(articlesStore, /coverImage: normalizeAdminArticleImageUrl\(/)
  assert.match(articlesStore, /url: normalizeAdminArticleImageUrl\(normalizedUrl\)/)
})

test('admin article store rewrites inline article image srcs for admin preview and editor', () => {
  assert.match(articlesStore, /const normalizeAdminArticleHtmlImages/)
  assert.match(articlesStore, /src=\(\["'\]\)\(\[\^"'\]\+\)\\1/ )
  assert.match(articlesStore, /data-tp-ref-image=\(\["'\]\)\(\[\^"'\]\+\)\\1/)
  assert.match(articlesStore, /normalizeAdminArticleImageUrl\(src\)/)
  assert.match(articlesStore, /contentHtml: normalizeAdminArticleHtmlImages\(/)
})
